import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Google.com - Clone By @SiddheshKukade (SIDDHESH BHUPENDRA KUKADE)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <h1 className=''>googel</h1>
      </Head>
    </div>
  )
}
