import Head from 'next/head'
import Image from 'next/image'
import Body from '../components/Body';
import styles from '../styles/Home.module.css'
import Header from './../components/Header';
import Footer from './../components/Footer';

export default function Home() {
  return (
    <div className='h-full' >
      <Head>
        <title>Google.com - Clone By @SiddheshKukade (SIDDHESH BHUPENDRA KUKADE)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Header */}
      <Header />
      {/* Body */}
      <Body />
      <Footer />
    </div>
  )
}
